image : mcr.microsoft.com/dotnet/sdk:5.0-alpine

stages:
  - build
  - release

build:
  stage: build
  script:
    - dotnet build 

release:
  stage: release
  only:
    - master
  artifacts:
    paths:
      - publish/linux
  script:
    - dotnet publish -c Release -r linux-x64 -o ../publish/linux --self-contained true -p:PublishSingleFile=true Raznor/Raznor.fsproj