image : mcr.microsoft.com/dotnet/sdk:5.0-alpine

stages:
  - build
  - release-windows
  - release-linux

build:
  stage: build
  script:
    - dotnet build

release-windows:
  stage: release-windows
  only:
    - master
  artifacts:
    paths:
      - publish/windows
  script:
    - dotnet publish -c Release -r win10-x64 -o ../publish/windows Raznor/Raznor.fsproj --self-contained true

release-linux:
  stage: release-linux
  only:
    - master
  artifacts:
    paths:
      - publish/linux
  script:
    - dotnet publish -c Release -r linux-x64 -o ../publish/linux Raznor/Raznor.fsproj --self-contained true